turn_on:
  description: Включение бинарного сенсора.
  fields:
    entity_id:
      description: Имя включаемой сущности
      example: 'binary_sensor.test'

turn_off:
  description: Выключение бинарного сенсора.
  fields:
    entity_id:
      description: Имя выключаемой сущности
      example: 'binary_sensor.test'

toggle:
  description: Переключение бинарного сенсора
  fields:
    entity_id:
      description: Имя переключаемой сущности
      example: 'binary_sensor.test'

set:
  description: Задать значение сенсора.
  fields:
    entity_id:
      description: Имя сущности, которой задается значение
      example: 'sensor.'
    value:
      description: задаваемое значение
      example: 25

set_available:
  description: Задать доступность сущности.
  fields:
    entity_id:
      description: Имя сущности
      example: 'switch.test'
    value:
      description: Value to set
      example: false
